"""Write the follower-pressure kernels into ``panels/models/<model>_num.pyx``

The kernels ``calc_fext_follower`` and ``fkCfollower_num`` of each model of
``follower_pressure.MODELS`` are generated from the expressions of
``follower_pressure.py`` and written between the markers ``BEGIN`` and
``END`` at the end of each ``_num.pyx``, replacing a previous version::

    python write_pyx.py [model ...]

The generators of whole modules, ``fsdt_tsdt/write_pyx.py`` and
``cylshell_clpt_sanders/write_pyx.py``, append the same block through
:func:`pyx_block`.

"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..', '..'))
sys.path.insert(0, HERE)

import follower_pressure as th

BEGIN = ('# BEGIN follower pressure, generated by '
         'theory/shells/follower_pressure/write_pyx.py\n')
END = '# END follower pressure\n'

BASIS = {
    # name: (f or g, field, derivative)
    'fAu': ('f', 'u', 0), 'fAuxi': ('f', 'u', 1),
    'fAv': ('f', 'v', 0), 'fAvxi': ('f', 'v', 1),
    'fAw': ('f', 'w', 0), 'fAwxi': ('f', 'w', 1),
    'gAu': ('g', 'u', 0), 'gAueta': ('g', 'u', 1),
    'gAv': ('g', 'v', 0), 'gAveta': ('g', 'v', 1),
    'gAw': ('g', 'w', 0), 'gAweta': ('g', 'w', 1),
}
FUNC = {0: 'f', 1: 'fp'}


def basis_line(name, index, indent):
    fg, field, der = BASIS[name.replace('B', 'A')]
    if fg == 'f':
        args = '{0}, xi, x1{1}, x1{1}r, x2{1}, x2{1}r'.format(index, field)
    else:
        args = '{0}, eta, y1{1}, y1{1}r, y2{1}, y2{1}r'.format(index, field)
    return '{0}{1} = {2}({3})'.format(' '*indent, name, FUNC[der], args)


def ordered(names):
    order = list(BASIS)
    return sorted(names, key=lambda n: order.index(n.replace('B', 'A')))


def pyx_block(model):
    r"""Source of the follower-pressure kernels of ``model``"""
    dof, geometry, kinematics = th.MODELS[model]
    cyl = geometry == 'cylshell'
    acode, kblocks = th.kernel_expressions(geometry, kinematics)
    point = sorted({s.name for e in acode for s in e.free_symbols}
                   & set(th.POINT_SUM), key=list(th.POINT_SUM).index)
    kpoint = sorted({s.name for e in kblocks.values() for s in e.free_symbols}
                    & set(th.POINT_SUM), key=list(th.POINT_SUM).index)
    used_fields = sorted({th.POINT_SUM[q][0] for q in point})
    fields = ''.join(th.FIELDS[i] for i in used_fields)

    def point_lines(names, indent):
        sp = ' '*indent
        out = [sp + ' = '.join(names) + ' = 0.']
        need = set()
        for q in names:
            need |= set(th.POINT_SUM[q][1].replace('(2/a)*', '').replace(
                '(2/b)*', '').split('*'))
        out.append(sp + 'for j in range(n):')
        for nm in ordered([nm for nm in need if nm.startswith('g')]):
            out.append(basis_line(nm, 'j', indent + 4))
        out.append(sp + '    for i in range(m):')
        for nm in ordered([nm for nm in need if nm.startswith('f')]):
            out.append(basis_line(nm, 'i', indent + 8))
        out.append(sp + '        col = col0 + DOF*(j*m + i)')
        for q in names:
            k, expr = th.POINT_SUM[q]
            out.append(sp + '        {0} += cs[col+{1}]*{2}'.format(q, k, expr))
        return out

    radius_cdef = '    cdef double r\n' if cyl else ''
    radius_read = '    r = shell.r\n' if cyl else ''
    bc_cdef = '\n'.join('    cdef double {0}1{1}, {0}1{1}r, {0}2{1}, {0}2{1}r'
                        .format(d, f) for d in 'xy' for f in 'uvw')
    bc_read = '\n'.join(
        '    {0}1{1} = shell.{0}1{1}; {0}1{1}r = shell.{0}1{1}r; '
        '{0}2{1} = shell.{0}2{1}; {0}2{1}r = shell.{0}2{1}r'.format(d, f)
        for d in 'xy' for f in 'uvw')
    pcdef = '    cdef double ' + ', '.join(th.POINT_SUM) + '\n'
    common_cdef = '''    cdef double a, b, pintx, pinty, qf
{radius}    cdef int m, n, nx, ny
{bc}

    cdef int i, j, k, l, c, col, row, ptx, pty
    cdef double xi, eta, weight
{pcdef}    cdef double [::1] xis, etas, weights_xi, weights_eta
'''.format(radius=radius_cdef, bc=bc_cdef, pcdef=pcdef)

    common_read = '''    if not 'Shell' in shell.__class__.__name__:
        raise ValueError('a Shell object must be given as input')
    a = shell.a
    b = shell.b
    m = shell.m
    n = shell.n
{radius}{bc}

    nx = pnxny.shape[0]
    ny = pnxny.shape[1]
    xis, weights_xi = roots_legendre(nx)
    etas, weights_eta = roots_legendre(ny)
    pintx = px2 - px1
    pinty = py2 - py1
    qf = 1. if quadratic else 0.
'''.format(radius=radius_read, bc=bc_read)

    point_map = '''                # Gauss point of the patch, in the natural coordinates of
                # the approximation functions, which span 0 <= x <= a and
                # 0 <= y <= b
                xi = 2*(px1 + (xis[ptx] + 1)/2*pintx)/a - 1
                eta = 2*(py1 + (etas[pty] + 1)/2*pinty)/b - 1
                weight = (weights_xi[ptx]*weights_eta[pty]*pintx*pinty/4
                          *pnxny[ptx, pty])'''

    # calc_fext_follower
    out = [BEGIN, '''

def calc_fext_follower(double [::1] cs, double [:, ::1] pnxny,
        double px1, double px2, double py1, double py2, object shell,
        int size, int col0, int quadratic=0, int reference=1):
    r"""Force vector of a follower pressure in the configuration ``cs``

    Integrates ``F_p = int p (Nu ax + Nv ay + Nw az) dA`` over the patch
    ``px1 <= x <= px2``, ``py1 <= y <= py2``, with ``nx x ny`` Gauss-Legendre
    points, ``(nx, ny) = pnxny.shape``, being ``pnxny[ptx, pty]`` the pressure,
    already multiplied by the load factor, at each point. The area vector
    ``(ax, ay, az)`` of the deformed mid-surface is, see
    ``theory/shells/follower_pressure``::

{adoc}

    with ``qf = 1`` for ``quadratic=1`` and ``qf = 0`` otherwise, and ``ref =
    1`` for ``reference=1``, which includes the dead part ``F_p(0)``, and
    ``ref = 0`` otherwise.

    """
'''.format(adoc='\n'.join('        a%s = %s' % (c, th.pstr(e))
                          for c, e in zip('xyz', acode)))]
    out.append(common_cdef)
    out.append('    cdef double ref, ax, ay, az\n')
    out.append('    cdef double fAu, fAuxi, fAv, fAvxi, fAw, fAwxi\n')
    out.append('    cdef double gAu, gAueta, gAv, gAveta, gAw, gAweta\n')
    out.append('    cdef double [::1] fext\n\n')
    out.append(common_read)
    out.append('''    ref = 1. if reference else 0.

    fext = np.zeros(size, dtype=DOUBLE)

    with nogil:
        for ptx in range(nx):
            for pty in range(ny):
{map}

                # displacement gradients at the Gauss point
'''.format(map=point_map))
    out.append('\n'.join(point_lines(point, 16)) + '\n\n')
    for comp, e in zip('xyz', acode):
        out.append('                a{0} = {1}\n'.format(comp, th.pstr(e)))
    out.append('''
                for j in range(n):
                    gAu = f(j, eta, y1u, y1ur, y2u, y2ur)
                    gAv = f(j, eta, y1v, y1vr, y2v, y2vr)
                    gAw = f(j, eta, y1w, y1wr, y2w, y2wr)
                    for i in range(m):
                        fAu = f(i, xi, x1u, x1ur, x2u, x2ur)
                        fAv = f(i, xi, x1v, x1vr, x2v, x2vr)
                        fAw = f(i, xi, x1w, x1wr, x2w, x2wr)
                        col = col0 + DOF*(j*m + i)
                        fext[col+0] += weight*fAu*gAu*ax
                        fext[col+1] += weight*fAv*gAv*ay
                        fext[col+2] += weight*fAw*gAw*az

    return fext

''')

    # fkCfollower_num
    blocks = sorted(kblocks.items())
    names = set()
    for _, e in blocks:
        names |= {s.name for s in e.free_symbols if s.name[:2] in
                  ('fA', 'gA', 'fB', 'gB')}
    # the basis functions of the point quantities, see point_lines()
    for q in kpoint:
        names |= set(th.POINT_SUM[q][1].replace('(2/a)*', '').replace(
            '(2/b)*', '').split('*'))
    fA = ordered([nm for nm in names if nm.startswith('fA')])
    fB = ordered([nm for nm in names if nm.startswith('fB')])
    gA = ordered([nm for nm in names if nm.startswith('gA')])
    gB = ordered([nm for nm in names if nm.startswith('gB')])
    out.append('''
def fkCfollower_num(double [::1] cs, double [:, ::1] pnxny,
        double px1, double px2, double py1, double py2, object shell,
        int size, int row0, int col0, int quadratic=0):
    r"""Load stiffness ``-dF_p/dc`` of a follower pressure

    See :func:`.calc_fext_follower` for the parameters. The matrix is
    unsymmetric in general, so it is assembled in full, not as an upper
    triangle, and must not be symmetrized. With ``quadratic=0`` it does not
    depend on ``cs``.

    """
''')
    out.append(common_cdef)
    out.append('    cdef long [::1] kCr, kCc\n    cdef double [::1] kCv\n')
    out.append('    cdef double ' + ', '.join(fA + fB) + '\n')
    out.append('    cdef double ' + ', '.join(gA + gB) + '\n\n')
    out.append(common_read)
    out.append('''
    fdim = {nb}*m*m*n*n
    kCr = np.zeros((fdim,), dtype=INT)
    kCc = np.zeros((fdim,), dtype=INT)
    kCv = np.zeros((fdim,), dtype=DOUBLE)

    with nogil:
        for ptx in range(nx):
            for pty in range(ny):
{map}

                # displacement gradients at the Gauss point, only used by the
                # quadratic area vector
'''.format(nb=len(blocks), map=point_map))
    if kpoint:
        pl = point_lines(kpoint, 20)
        out.append('                ' + ' = '.join(kpoint) + ' = 0.\n')
        out.append('                if quadratic == 1:\n')
        out.append('\n'.join(pl[1:]) + '\n')
    out.append('\n                c = -1\n                for i in range(m):\n')
    out += [basis_line(nm, 'i', 20) + '\n' for nm in fA]
    out.append('                    for k in range(m):\n')
    out += [basis_line(nm, 'k', 24) + '\n' for nm in fB]
    out.append('                        for j in range(n):\n')
    out += [basis_line(nm, 'j', 28) + '\n' for nm in gA]
    out.append('                            for l in range(n):\n')
    out += [basis_line(nm, 'l', 32) + '\n' for nm in gB]
    out.append('''                                row = row0 + DOF*(j*m + i)
                                col = col0 + DOF*(l*m + k)
''')
    for (i, j), e in blocks:
        out.append('''                                c += 1
                                if ptx == 0 and pty == 0:
                                    kCr[c] = row+{i}
                                    kCc[c] = col+{j}
                                kCv[c] += weight*( {e} )
'''.format(i=i, j=j, e=th.pstr(e)))
    out.append('''
    kC = coo_matrix((kCv, (kCr, kCc)), shape=(size, size))

    return kC
''')
    out.append(END)
    return ''.join(out)


def insert_block(model):
    path = os.path.join(REPO, 'panels', 'models', model + '_num.pyx')
    with open(path) as f:
        text = f.read()
    if BEGIN in text:
        start = text.index(BEGIN)
        end = text.index(END) + len(END)
        text = text[:start].rstrip('\n') + '\n\n\n' + text[end:].lstrip('\n')
    text = text.rstrip('\n') + '\n\n\n' + pyx_block(model)
    with open(path, 'w', newline='\n') as f:
        f.write(text)
    print(model, 'follower pressure kernels written')


if __name__ == '__main__':
    for model in sys.argv[1:] or th.MODELS:
        insert_block(model)
